# Project information
site_name: "Programming Fundamentals"
site_description: "Programming Concepts"
site_url: "https://santosh-1987.github.io/programming-fundamentals/"

# Repository
# repo_name: "Click here to edit"
# repo_url: "https://github.com/santosh-1987/programming-fundamentals"
# edit_uri: "https://github.com/santosh-1987/programming-fundamentals/blob/master/docs"

nav:
  - Home: index.md
  - Program Constructs:
    - Construct Definition: programming-constructs/index.md
    - Sequence: programming-constructs/sequence.md
    - Selection: programming-constructs/selection.md
    - Iteration: programming-constructs/repetition.md
    - Routine Invocation: programming-constructs/routine_invocation.md
  - Search Algorithms:
      - Saerch Concept: search-algorithms/search.md
      - Linear Search: search-algorithms/linear-search.md
      - Binary Search: search-algorithms/binary-search.md
  - Recursion: recursion/recursion.md

# Configuration
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - ruby
  include_homepage_in_sidebar: true
  collapse_navigation: true
  logo: "assets/images/logo.jpeg"
  favicon: "assets/images/favicon.jpeg"
  feature:
    - navigation.tabs
  language: "en"
  palette:
    primary: "teal"
    accent: "green"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    - search.suggest
    - search.highlight
    - search.share
extra_css:
  - custom.css
extra:
  search:
    tokenizer: '[\s\-\.]+'
  version:
    provider: mike

plugins:
  - search:
     separator: '[\s\-\.]+'
     prebuild_index: true

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
      baselevel: 2
