# Project information
site_name: "Programming Fundamentals"
site_description: "Programming Concepts"
site_url: "https://santosh-1987.github.io/programming-fundamentals/"

# Repository
# repo_name: "Click here to edit"
# repo_url: "https://github.com/santosh-1987/programming-fundamentals"
# edit_uri: "https://github.com/santosh-1987/programming-fundamentals/blob/master/docs"

nav:
  - Home: index.md
  - Terminologies:
      - Computer Basics: computer_basics/terminology.md
      - Byte System: computer_basics/currency_byte_system.md
  - Program Constructs:
      - Construct Definition: programming-constructs/index.md
      - Sequence: programming-constructs/sequence.md
      - Selection: programming-constructs/selection.md
      - Iteration: programming-constructs/repetition.md
      - Routine Invocation: programming-constructs/routine_invocation.md
  - Search Algorithms:
      - Search Concept: search-algorithms/search.md
      - Linear Search: search-algorithms/linear-search.md
      - Binary Search: search-algorithms/binary-search.md
  - Loops:
      - Loop: loops/index.md
      - Recursion: loops/recursion.md
  - Bit Manipulation:
      - Logical Operator: bit-manipulation/bit_manipulation.md
      - Shift Operator: bit-manipulation/shift_operator.md
  - Time & Space Complexity:
      - Time Complexity: TimeComplexity/time_complexity_basics.md
      - Space Complexity: TimeComplexity/time_and_space_complexity.md
  - Arrays:
      - Introduction: arrays/introduction.md
      - Prefix Sum: arrays/prefix_sum.md
      - Carry Forward Technique: arrays/array_carry_forward.md
      - Maths: arrays/maths.md
      - Sorting Introduction: arrays/sorting.md
  - Strings:
      - Introduction: strings/introduction.md
  - Hashing:
      - Introduction: hashing/hashing-intro.md
  - Algorithms:
      - Manachers Algorithm: algorithms/manachers_algorithm.md
      - Kadanes Algorithm: algorithms/kadanes_algorithm.md
  - Low Level Design:
      - How to Approach Design Problem: lld/how_to_approach_design_problems.md
      - Design a Pen: lld/design-a-pen.md
# Configuration
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - ruby
  include_homepage_in_sidebar: true
  collapse_navigation: true
  logo: "assets/images/logo.jpeg"
  favicon: "assets/images/favicon.jpeg"
  language: "en"
  palette:
    primary: "teal"
    accent: "green"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.tabs.expand
    - navigation.instant.prefetch
    - navigation.tracking
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
extra:
  search:
    tokenizer: '[\s\-\.]+'
  version:
    provider: mike

plugins:
  - glightbox
  - table-reader
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      prebuild_index: true

# Extensions
markdown_extensions:
  - tables
  - admonition
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format